name: Create Name JSON

on:
  workflow_dispatch:
    inputs:
      name:
        description: "The username to approve"
        required: true

permissions:
  contents: write

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create JSON file
        run: |
          safe="${{ github.event.inputs.name }}"
          mkdir -p names
          echo '{ "approved": false }' > names/${safe}.json

      - name: Commit & push
        run: |
          git config user.name "sparx-bot"
          git config user.email "sparx@example.com"
          git add names/
          git commit -m "Add ${safe}.json"
          git push
