name: Create Name JSON File

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Name to create JSON for (no spaces)'
        required: true
        default: 'kiyannaqvi'

jobs:
  create_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create JSON file for user
        run: |
          NAME="${{ github.event.inputs.username }}"
          echo "{\"approved\": false}" > names/${NAME}.json
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add names/${NAME}.json
          git commit -m "Add JSON for $NAME"
          git push
