name: Add New Name

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name to approve (e.g. 'Kiyan Naqvi')"
        required: true

jobs:
  createFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Format username
        id: format
        run: |
          SAFE_NAME=$(echo "${{ github.event.inputs.name }}" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          echo "SAFE_NAME=$SAFE_NAME" >> $GITHUB_ENV

      - name: Create JSON file
        run: |
          mkdir -p names
          echo '{ "approved": true }' > "names/${{ env.SAFE_NAME }}.json"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add names/${{ env.SAFE_NAME }}.json
          git commit -m "Add approval for ${{ github.event.inputs.name }}"
          git push
