name: Demo Create Name JSON

on:
  workflow_dispatch:  # manual trigger

jobs:
  create_json_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create example JSON
        run: |
          echo '{"approved": false}' > names/example.json
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add names/example.json
          git commit -m "Add example.json via GitHub Actions"
          git push
