name: Create Name JSON

on:
  repository_dispatch:
    types: [create-name-json]

jobs:
  create_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create JSON file
        env:
          NAME: ${{ github.event.client_payload.name }}
          SAFE_NAME: ${{ github.event.client_payload.name | toLowerCase | replace(' ', '') }}
        run: |
          SAFE_NAME=$(echo "$NAME" | tr '[:upper:]' '[:lower:]' | tr -d ' ')
          echo "{\"approved\": false}" > names/${SAFE_NAME}.json
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add names/${SAFE_NAME}.json
          git commit -m "Add approval file for $NAME"
          git push
